title: 'Pietro Bardini'
description: "Pietro Bardini | Artist"

header_pages:
  - home.md
  - cv.md
  - IDMCITDHIL.md
  - CorpusAlign.md
  - PD1.md
  - SL_genCore.md

style: light 

footer: '<a href="https://instagram.com/pietrobardini">IG</a>'

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
