title: 'Pietro Bardini'
description: "Pietro Bardini | Artist"

header_pages:
  - home.md
  - cv.md
  - IDMCITDHIL.md
  - corpusAlign.md
  - PD1.md
  
  

style: light 

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
