title: 'Pietro Bardini'
description: "Pietro Bardini | Artist"

header_pages:
  - index.md
  - peter.md
  - cv.md
  - contact.md

style: light 

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
